---
title: Carolina Amateur Radio Club
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: rouge
permalink: pretty
description: Expanding communication interest and technical knowledge to amateurs
  and non-amateurs alike.
url: http://www.carolinaradioclub.com
baseurl: "http://www.carolinaradioclub.com/"
author:
  name: Roy Williams
  url: https://www.fang64.com
paginate: 5
version: 1.0.0
github:
  repo: https://github.com/CarolinaAmateurRadioClub/Website
