---
title: Carolina Amateur Radio Club
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
highlighter: rouge
permalink: pretty
repository: CarolinaAmateurRadioClub/Website
description: Expanding communication interest and technical knowledge to amateurs
  and non-amateurs alike.
meetingaddress: '<strong>The Church Lincolnton<br>1591 Startown Rd<br>Lincolnton, NC 28092</strong>'
covidnotice: '**٭٭WE HAVE RESUMED TESTING & CLUB MEETINGS ARE SUSPENDED UNTIL POSTED ELSEWHERE AS OF 6/6/2021.  SOCIAL DISTANCING WILL BE IN EFFECT AT ALL MEETINGS & TEST SESSIONS AND MASKS WILL BE REQUIRED.  THANK YOU FOR YOUR UNDERSTANDING DURING THIS DIFFICULT TIME٭٭**{: style="color: red;" }'
url: http://www.carolinaradioclub.com
baseurl: "" 
author:
  name: Les Cline
  url: 
paginate: 5
version: 2.0.0
github:
  repo: https://github.com/CarolinaAmateurRadioClub/Website
